### ISSUE TITLE
incompatible Defaults for functions vs Struct Deserializers

### ISSUE THREAD

**Issue by apgoetz** [servo/bincode#372] opened 2021-02-22 05:01 UTC
the `serialize` and `deserialize` functions use different defaults than the `DefaultOptions` Struct. Specifically, the functions use a `fixedint` format, but DefaultOptions uses `varint`.

Confusingly, both the function documentation and the Struct documentation indicate that they use the default options. 

I ran into this issue, because I am writing some code that needs to use `serde::de::DeserializeSeed`, which requires access to the `Deserializer` as a struct. However, the data may not be created with the struct, as most `bincode` usage seems to use the functions. 

Steps to reproduce: 

```rust
extern crate bincode;
extern crate serde;

#[test]
fn test_mix_fn_and_struct() {
    // example data
    let orig = ("abc", 1, 2, 3);

    // serialize using fn 
    let encoded: Vec<u8> = bincode::serialize(&orig).unwrap();

    // deserialize using struct
    let opts = bincode::DefaultOptions::new();
    let mut deserializer = bincode::Deserializer::from_slice(&encoded, opts);
    let output = <_ as serde::Deserialize>::deserialize(&mut deserializer).unwrap();
    // fails
    assert_eq!(orig, output);
    // ---- test_mix_fn_and_struct stdout ----
    // thread 'test_mix_fn_and_struct' panicked at 'assertion failed: `(left == right)`
    // left: `("abc", 1, 2, 3)`,
    // right: `("\u{0}\u{0}\u{0}", 0, 0, 0)`', tests/default.rs:13:5
}
```

**Comment by ZoeyR** [comment] 2021-02-22 09:51
Yeah, I messed up the documentation on this one. The reason `serialize` and `deserialize` use fixedint is to maintain backwards compatibility with older versions of bincode. Closing this as a duplicate of #348

**Closed by ZoeyR** 2021-02-22 09:51 UTC
